### PR TITLE
add pug engine

### PR DESCRIPTION
**Pull request by esmiralha**
adding pug engine

### CODE REVIEW

**Comment by gjuoun** [comment]
Thanks for you contribution @esmiralha , can you make sure the tests are passing?

**Comment by esmiralha** [comment]
Can I update the deno runtime used by the CI GH action to 1.29.1?

**Comment by esmiralha** [comment]
@gjuoun Are we good to merge? Thank you!

**Comment by gjuoun** [comment]
> @gjuoun Are we good to merge? Thank you!

Done.

**Pull request merged**
